### ISSUE TITLE
fix bug songs data

### ISSUE THREAD

**Issue by missile720** [missile720/music-player#136]
Some of the songs on Spotify don't have their music data available so it crashes the app when a song that doesn't have this data is selected.

**Comment by tkgonzal** [comment]
(question): Would you happen to know which specific songs cause the crash? We worked on debugging a similar bug in a previous pull request by having a check in the PlaylistContainer's useEffect to generate the songCards for a Spotify playlist where a songCard would only be made generated if it had valid song data so I might be able to help with that.
